### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by alesky78** [Dynamitos/PixelDungeon#1]
run the jar on distribution..
but the console generate several errors

C:\laboratorio\pixeldungeon\git-repo\PixelDungeon\dist>java -jar PixelDungeonz.jar > out
Bitmap failed
Bitmap failed
Bitmap failed
Bitmap failed
Bitmap failed
Bitmap failed
Bitmap failed
Bitmap failed
Bitmap failed
Bitmap failed
Bitmap failed
Bitmap failed
Bitmap failed
Bitmap failed
Bitmap failed
Bitmap failed
Bitmap failed
Bitmap failed
Bitmap failed
Exception in thread "main" java.lang.NullPointerException
        at pixeldungeon.textures.Texture.combine(Texture.java:38)
        at pixeldungeon.main.UIDrawer.drawDungeon(UIDrawer.java:60)
        at pixeldungeon.main.PixelMain.generate(PixelMain.java:61)
        at pixeldungeon.main.GamePanel.<init>(GamePanel.java:28)
        at pixeldungeon.main.Launcher.main(Launcher.java:7)

**Comment by Dynamitos** [comment]
Oh god why is this project still on github. I'm so ashamed of this project, since I wrote it when I just started learning java.
